version: "3.9"
services:
  mysql-standalone:
    container_name: property-tracker-db
    image: mysql:latest
    command:  --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=property_tracker"
    volumes:
      - ./data/db:/var/lib/mysql

  property-tracker:
    container_name: propert-tracker-app
    image: property-tracker-spring-image
    build:
      context: ..
      dockerfile: ../Dockerfile
    volumes:
      - /data/springboot-docker-compose-app
    ports:
      - "8081:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - "MYSQL_HOST=mysql-standalone"
    depends_on:
      - mysql-standalone